# mail.yml workflow file for Nikola to build the website from the source branch.
on: [push]

jobs:
  nikola_build:
    runs-on: ubuntu-latest
    name: 'Deploy Nikola to GitHub Pages'
    steps:
    - name: Check out
      uses: actions/checkout@v3
      with:
        set-safe-directory: '*'      
    - name: Build and Deploy Nikola
      uses: getnikola/nikola-action@v8
      #with:
      #  dry_run: false
